CREATE SCHEMA IF NOT EXISTS intramurudes;
SET search_path = intramurudes;

CREATE TABLE sport(
                      id INT GENERATED BY DEFAULT AS IDENTITY,
                      name VARCHAR(100) NOT NULL,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      PRIMARY KEY(id),
                      UNIQUE(name)
);

CREATE TABLE league(
                       id INT GENERATED BY DEFAULT AS IDENTITY,
                       name VARCHAR(127) NOT NULL,
                       week_day VARCHAR(20),
                       time_start TIME,
                       time_end TIME,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       id_sport INT NOT NULL,
                       PRIMARY KEY(id),
                       FOREIGN KEY(id_sport) REFERENCES sport(id)
);

CREATE TABLE team(
                     id INT GENERATED BY DEFAULT AS IDENTITY,
                     name VARCHAR(127) NOT NULL,
                     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                     id_league INT NOT NULL,
                     PRIMARY KEY(id),
                     FOREIGN KEY(id_league) REFERENCES league(id)
);

CREATE TABLE player(
                       id INT GENERATED BY DEFAULT AS IDENTITY,
                       name VARCHAR(127),
                       last_name VARCHAR(127),
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       id_team INT NOT NULL,
                       PRIMARY KEY(id),
                       FOREIGN KEY(id_team) REFERENCES team(id)
);

CREATE TABLE match_(
                       id INT GENERATED BY DEFAULT AS IDENTITY,
                       match_timestamp TIMESTAMP,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       PRIMARY KEY(id)
);

CREATE TABLE season(
                       id INT GENERATED BY DEFAULT AS IDENTITY,
                       season_year INT NOT NULL,
                       time_precision VARCHAR(127),
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       PRIMARY KEY(id)
);

CREATE TABLE stat_statement(
                               id INT GENERATED BY DEFAULT AS IDENTITY,
                               statement TEXT,
                               created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               PRIMARY KEY(id)
);

CREATE TABLE team_stat(
                          id INT GENERATED BY DEFAULT AS IDENTITY,
                          value_ VARCHAR(127),
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          id_season INT,
                          id_match INT NOT NULL,
                          id_stat_statement INT NOT NULL,
                          id_team INT NOT NULL,
                          PRIMARY KEY(id),
                          FOREIGN KEY(id_season) REFERENCES season(id),
                          FOREIGN KEY(id_match) REFERENCES match_(id),
                          FOREIGN KEY(id_stat_statement) REFERENCES stat_statement(id),
                          FOREIGN KEY(id_team) REFERENCES team(id)
);

CREATE TABLE player_stat(
                            id INT GENERATED BY DEFAULT AS IDENTITY,
                            value_ VARCHAR(127),
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            id_stat_statement INT NOT NULL,
                            id_season INT,
                            id_player INT NOT NULL,
                            PRIMARY KEY(id),
                            FOREIGN KEY(id_stat_statement) REFERENCES stat_statement(id),
                            FOREIGN KEY(id_season) REFERENCES season(id),
                            FOREIGN KEY(id_player) REFERENCES player(id)
);

CREATE TABLE role(
                     id INT GENERATED BY DEFAULT AS IDENTITY,
                     role_name VARCHAR(127),
                     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                     PRIMARY KEY(id)
);

CREATE TABLE user_(
                      id INT GENERATED BY DEFAULT AS IDENTITY,
                      username VARCHAR(127) NOT NULL,
                      password VARCHAR(127) NOT NULL,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      PRIMARY KEY(id),
                      UNIQUE(username)
);

CREATE TABLE log(
                    id INT GENERATED BY DEFAULT AS IDENTITY,
                    text TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY(id)
);

CREATE TABLE match_team(
                           id_team INT,
                           id_match INT,
                           PRIMARY KEY(id_team, id_match),
                           FOREIGN KEY(id_team) REFERENCES team(id),
                           FOREIGN KEY(id_match) REFERENCES match_(id)
);

CREATE TABLE league_season(
                              id_league INT,
                              id_season INT,
                              PRIMARY KEY(id_league, id_season),
                              FOREIGN KEY(id_league) REFERENCES league(id),
                              FOREIGN KEY(id_season) REFERENCES season(id)
);

CREATE TABLE role_user(
                          id_role INT,
                          id_user INT,
                          PRIMARY KEY(id_role, id_user),
                          FOREIGN KEY(id_role) REFERENCES role(id),
                          FOREIGN KEY(id_user) REFERENCES user_(id)
);

CREATE TABLE stat_statement_sport(
                                     id_sport INT,
                                     id_stat_statement INT,
                                     PRIMARY KEY(id_sport, id_stat_statement),
                                     FOREIGN KEY(id_sport) REFERENCES sport(id),
                                     FOREIGN KEY(id_stat_statement) REFERENCES stat_statement(id)
);

ALTER TABLE league ADD CONSTRAINT league_name_sport_id_unique UNIQUE  (name, id_sport);

ALTER TABLE team ADD CONSTRAINT team_name_league_id UNIQUE (name, id_league);


