include:
  - ./docker/auth.yml
  - ./docker/database.yml
  - ./docker/webserver.yml

services:
  application:
    container_name: application
    build:
      dockerfile: ./Dockerfile
    depends_on:
      webserver:
        condition: service_started
      auth:
        condition: service_started
      database:
        condition: service_healthy
    ports:
      - 8888:8888
    networks:
      - acad-net

networks:
  acad-net:
    driver: bridge
