services:
  webserver:
    image: openquantumsafe/nginx-quic:latest
    container_name: webserver
    volumes:
      - ./webserver/cert:/etc/nginx/cert
      - ./webserver/includes:/etc/nginx/includes
      - ./webserver/html:/usr/share/nginx/html
      - ./webserver/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - auth
      - database
    networks:
      acad-net:
  auth:
    image: quay.io/keycloak/keycloak:19.0.3
    container_name: auth
    volumes:
      - ./keycloak/data:/var/tmp
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
    entrypoint: sh -c "
      echo 'starting keycloak...' &&
      /opt/keycloak/bin/kc.sh start-dev --http-port 8180 &
  
      echo 'waiting for keycloak...' &&
      timeout 300 bash -c 'until curl -s http://localhost:8180 > /dev/null; do sleep 5; done' &&
      
      echo 'initializing realm...' &&
      /opt/keycloak/bin/kcadm.sh config credentials --server http://localhost:8180/ --realm master --user admin --password admin &&
      /opt/keycloak/bin/kcadm.sh create realms -s realm=usager -s enabled=true -o &&
      test -f /var/tmp/frontend.json && /opt/keycloak/bin/kcadm.sh create clients -r usager -f /var/tmp/frontend.json &&
      test -f /var/tmp/backend.json && /opt/keycloak/bin/kcadm.sh create clients -r usager -f /var/tmp/backend.json &&
      test -f /var/tmp/users.json && /opt/keycloak/bin/kcadm.sh create partialImport -r usager -s ifResourceExists=OVERWRITE -f /var/tmp/users.json &&
      tail -f /dev/null
      "
    ports:
      - 8180:8180
    networks:
      acad-net:

  database:
    image: postgres:13
    container_name: database
    restart: always
    ports:
      - 5444:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    networks:
      acad-net:

networks:
  acad-net: