services:
  webserver:
   image: openquantumsafe/nginx-quic:latest
   container_name: webserver
   volumes:
     - ./webserver/cert:/etc/nginx/cert
     - ./webserver/includes:/etc/nginx/includes
     - ./webserver/html:/usr/share/nginx/html
     - ./webserver/nginx.conf:/etc/nginx/nginx.conf
   ports:
     - 81:80
     - 444:443
   depends_on:
     - auth
     - database
   networks:
     acad-net:
